#!/bin/bash
set -e

wait-for-ok-cpu-load

(
    set +e
    stumpwm > stumpwm.stdout.txt 2> stumpwm.stderr.txt
    ec="$?"
    set -e
    if [ "$ec" != 0 ]; then
        echo "stumpwm exited with code $ec" >> "fail"
    fi
) &
stumpwm-cmd eval nil # Wait for stumpwm to start
sleep 1 # Wait for screen to refresh
