#!/bin/bash
set -e

startup_width="$1"
startup_height="$2"
Xvfb "$DISPLAY" -screen 0 "${startup_width}x${startup_height}x24" &
# Wait for Xvfb to start
while ! xset q &>/dev/null; do sleep .5; done
sleep 1
